---
linters:
  enable-all: true
  disable:
    - exportloopref # WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - err113 # WARN [lintersdb] The name "goerr113" is deprecated. The linter has been renamed to: err113
    - gomnd # WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd
    - tagliatelle
    - wsl
    - nlreturn
    - lll
    - godot
    - varnamelen
    - ireturn
    - depguard
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - godox
    - nestif
    - funlen
    - gocognit
    - gocyclo
    - exhaustruct
    - execinquery
    - dupword
    - musttag
