title: Deprecated (Bug Report)
body:
  - type: markdown
    attributes:
      value: |
        ## :warning: Please use the issue template instead

        We don't accept new discussions anymore.
        We keep this discussion category only for existing discussions.

        [Please create an issue](https://github.com/suzuki-shunsuke/tfcmt/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml).
  # At least one input item is required, so we add a dummy checkbox.
  - type: checkboxes
    attributes:
      label: .
      options:
        - label: ..
