name: Support Request
description: |
  Please use this template when you face any problem (not bug) and need our help.
  If you're not sure if it's a bug or not, please use this template.
labels:
  - support-request
body:
  - type: textarea
    id: tfcmt-version
    attributes:
      label: tfcmt version
      description: Please use the latest version.
      value: |
        ```console
        $ tfcmt -v

        ```
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        * OS (Windows, Linux, macOS, etc)
        * CPU Architecture (amd64, arm64, etc)
      value: |
        * OS:
        * CPU Architecture:
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        Please see [the guide](https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce) too.
        tfcmt.yaml should be not partial but complete configuration.
        Please remove unneeded configuration to reproduce the issue.
      value: |
        tfcmt.yaml

        ```yaml

        ```

        Terraform Configuration
 
        ```tf

        ```

        Executed command and output

        ```console
        $ 
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
    validations:
      required: false
