#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname "$0")/.."

echo "---
sidebar_position: 600
---

# Command Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$(tfcmt help-all)" > docs/usage.md
