---
name: Deploy GitHub Pages (workflow_call)
on: workflow_call
permissions: {}
jobs:
  deploy-doc:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
    steps:
      - uses: suzuki-shunsuke/release-doc-action@feat-add-source_dir
        with:
          issue_number: 1724
          source_dir: site
          publish_dir: site/build
          destination_dir: docs
